version: '3'

services:
    mercure:
        image: dunglas/mercure
        ports: ['3000:80']
        environment:
            - ALLOW_ANONYMOUS=1
            - DEMO=1
            - CORS_ALLOWED_ORIGINS=*
            - JWT_KEY=!UnsecureChangeMe!

    mysql:
        image: 'mysql:5.7'
        environment:
            - MYSQL_DATABASE=mercure_workshop
            - MYSQL_USER=mercure_workshop
            - MYSQL_PASSWORD=mercure_workshop
            - MYSQL_ROOT_PASSWORD=mercure_workshop

    php:
        build: ./docker/php/
        working_dir: /usr/share/nginx/html
        links:
            - mysql
            - mercure
        volumes:
            - './:/usr/share/nginx/html'
            - ~/.composer/cache:/root/.composer/cache

    nginx:
        image: 'okty/nginx:1.14'
        working_dir: /usr/share/nginx/html
        ports: ['8080:80']
        links: [php]
        volumes: ['./:/usr/share/nginx/html']
        environment:
            - PHP_CONTAINER_ID=php
            - INDEX_SUBFOLDER=public
